/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        outline: "var(--color-outline)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "inverse-surface": "var(--color-inverse-surface)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "surface-container-high": "var(--color-surface-container-high)",
        "primary-fixed": "var(--color-primary-fixed)",
        "surface-tint": "var(--color-surface-tint)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "on-secondary": "var(--color-on-secondary)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "outline-variant": "var(--color-outline-variant)",
        "secondary-container": "var(--color-secondary-container)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        error: "var(--color-error)",
        "on-primary-container": "var(--color-on-primary-container)",
        "on-primary": "var(--color-on-primary)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "surface-dim": "var(--color-surface-dim)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "surface-variant": "var(--color-surface-variant)",
        primary: "var(--color-primary)",
        surface: "var(--color-surface)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        background: "var(--color-background)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "surface-container": "var(--color-surface-container)",
        "on-error-container": "var(--color-on-error-container)",
        "surface-bright": "var(--color-surface-bright)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "on-background": "var(--color-on-background)",
        "on-tertiary": "var(--color-on-tertiary)",
        "on-error": "var(--color-on-error)",
        tertiary: "var(--color-tertiary)",
        secondary: "var(--color-secondary)",
        "inverse-primary": "var(--color-inverse-primary)",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "primary-container": "var(--color-primary-container)",
        "error-container": "var(--color-error-container)",
        entrada: "var(--color-entrada)",
        saida: "var(--color-saida)",
        primaria: "var(--color-primaria)",
        laranja: "var(--color-laranja)",
        azul: "var(--color-azul)",
        ink: "var(--color-ink)",
        paper: "var(--color-paper)",
        "stamp-accent": "var(--color-stamp-accent)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "tertiary-container": "var(--color-tertiary-container)",
        "on-surface": "var(--color-on-surface)",
        line: "var(--color-line)",
        card: "var(--bg-card)",
        "input-surface": "var(--bg-input)",
      },
      spacing: {
        "receipt-width": "480px",
        "stack-loose": "2rem",
        "margin-page": "2rem",
        gutter: "1rem",
        "stack-base": "1rem",
        "stack-tight": "0.25rem",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
      },
      fontFamily: {
        "headline-md": ["Anybody"],
        "label-caps": ["IBM Plex Mono"],
        "value-sm": ["IBM Plex Mono"],
        "headline-lg": ["Big Shoulders Display"],
        "body-lg": ["IBM Plex Sans"],
        "value-lg": ["IBM Plex Mono"],
        "body-sm": ["IBM Plex Sans"],
        "headline-xl": ["Big Shoulders Display"],
        "headline-lg-mobile": ["Big Shoulders Display"],
        "body-md": ["IBM Plex Sans"],
        "data-lg": ["IBM Plex Mono"],
        "data-md": ["IBM Plex Mono"],
      },
      fontSize: {
        "headline-md": [
          "24px",
          { lineHeight: "110%", letterSpacing: "0.02em", fontWeight: "700" },
        ],
        "label-caps": [
          "12px",
          { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "700" },
        ],
        "value-sm": [
          "14px",
          { lineHeight: "120%", fontWeight: "500" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "700" },
        ],
        "body-lg": [
          "16px",
          { lineHeight: "150%", fontWeight: "400" },
        ],
        "value-lg": [
          "20px",
          { lineHeight: "120%", fontWeight: "600" },
        ],
        "body-sm": [
          "14px",
          { lineHeight: "1.5", fontWeight: "400" },
        ],
        "headline-xl": [
          "48px",
          { lineHeight: "1.1", letterSpacing: "0.02em", fontWeight: "800" },
        ],
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "1.2", fontWeight: "700" },
        ],
        "body-md": [
          "16px",
          { lineHeight: "1.6", fontWeight: "400" },
        ],
        "data-lg": [
          "20px",
          { lineHeight: "1.4", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "data-md": [
          "16px",
          { lineHeight: "1.4", fontWeight: "500" },
        ],
      },
      boxShadow: {
        card: 'var(--shadow)',
        'card-hover': '0 4px 12px rgba(0, 0, 0, 0.12)',
      },
      maxWidth: {
        "receipt-width": "480px",
      },
    },
  },
  plugins: [],
};
