/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        outline: "#747874",
        "on-tertiary-fixed-variant": "#105137",
        "inverse-surface": "#313128",
        "tertiary-fixed": "#b1f0cd",
        "surface-container-high": "#ece8db",
        "primary-fixed": "#dfe4df",
        "surface-tint": "#5a605c",
        "on-secondary-fixed": "#191c1a",
        "on-secondary-fixed-variant": "#444745",
        "secondary-fixed-dim": "#c5c7c3",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#002113",
        "outline-variant": "#c4c7c3",
        "secondary-container": "#dee0dc",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#606360",
        "surface-container-highest": "#e6e2d6",
        "inverse-on-surface": "#f4f1e4",
        error: "#ba1a1a",
        "on-primary-container": "#868b87",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#c3c8c3",
        "surface-dim": "#dddace",
        "on-primary-fixed-variant": "#434844",
        "surface-variant": "#e6e2d6",
        primary: "#090e0b",
        surface: "#fdf9ec",
        "on-surface-variant": "#444845",
        background: "#fdf9ec",
        "secondary-fixed": "#e1e3df",
        "surface-container": "#f1eee1",
        "on-error-container": "#93000a",
        "surface-bright": "#fdf9ec",
        "on-primary-fixed": "#181d1a",
        "on-background": "#1c1c14",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        tertiary: "#001008",
        secondary: "#5c5f5c",
        "inverse-primary": "#c3c8c3",
        "surface-container-low": "#f7f4e7",
        "on-tertiary-container": "#5a9677",
        "primary-container": "#1f2421",
        "error-container": "#ffdad6",
        "entrada": "#105137",
        "saida": "#ba1a1a",
        ink: "#090e0b",
        paper: "#fdf9ec",
        "stamp-accent": "#5a9677",
        "tertiary-fixed-dim": "#96d4b2",
        "tertiary-container": "#002919",
      },
      spacing: {
        "receipt-width": "480px",
        "stack-loose": "2rem",
        "margin-page": "2rem",
        gutter: "1rem",
        "stack-base": "1rem",
        "stack-tight": "0.25rem",
      },
      fontFamily: {
        "headline-md": ["Anybody"],
        "label-caps": ["IBM Plex Mono"],
        "value-sm": ["IBM Plex Mono"],
        "headline-lg": ["Anybody"],
        "body-lg": ["IBM Plex Sans"],
        "value-lg": ["IBM Plex Mono"],
        "body-sm": ["IBM Plex Sans"],
      },
      fontSize: {
        "headline-md": [
          "24px",
          { lineHeight: "110%", letterSpacing: "0.02em", fontWeight: "700" },
        ],
        "label-caps": [
          "11px",
          { lineHeight: "100%", letterSpacing: "0.1em", fontWeight: "700" },
        ],
        "value-sm": [
          "14px",
          { lineHeight: "120%", fontWeight: "500" },
        ],
        "headline-lg": [
          "40px",
          { lineHeight: "100%", letterSpacing: "0.05em", fontWeight: "800" },
        ],
        "body-lg": [
          "16px",
          { lineHeight: "150%", fontWeight: "400" },
        ],
        "value-lg": [
          "20px",
          { lineHeight: "120%", fontWeight: "600" },
        ],
        "body-sm": [
          "14px",
          { lineHeight: "140%", fontWeight: "400" },
        ],
      },
      maxWidth: {
        "receipt-width": "480px",
      },
    },
  },
  plugins: [],
};
